spring:
  cloud:
    config:
      server:
        git:
          #link to local config repo for developing
          uri: file://\${user.home}/${configDir}
#          uri: https://github.com/{username}/{repo}
#          searchPaths: folder with configs in repo (optional if repo contains only configs)
server:
  port: 8080

#Encryption configuration to encrypt properties in config files
encrypt:
  #keystore settings to use encryption with an asymmetric key
  keyStore:
    location: classpath:/server.jks
    password: f865230af8c84
    alias: config-server
    secret: f865230af8c84
  #key to use encryption with a symmetric key
  #key: {KEY_VALUE}

#user name and password to protect config server
security:
  user:
    name: user
    password: f865230af8c84
